In [1]:

import numpy as np
import scipy.stats as stats
import pandas as pd


# this line tells jupyter notebook to put the plots in the notebook rather than saving them to file.
%matplotlib inline

# this line makes plots prettier on mac retina screens. If you don't have one it shouldn't do anything.
%config InlineBackend.figure_format = 'retina'

In [2]:
# check the iowa file location for your computer 
iowa_file = 'Iowa_Liquor_sales_sample_10pct.csv'

iowa = pd.read_csv(iowa_file)
print "Dataframe is of size: " + str(iowa.values.nbytes / 10**6) + "MB"

Dataframe is of size: 39MB

In [3]:
iowa.describe()

/Users/aishwaryachinnari/anaconda/envs/dsi/lib/python2.7/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Store Number,County Number,Category,Vendor Number,Item Number,Bottle Volume (ml),Bottles Sold,Volume Sold (Liters),Volume Sold (Gallons)
count,270955.000000,269878.000000,2.708870e+05,270955.00000,270955.000000,270955.000000,270955.000000,270955.000000,270955.000000
mean,3590.263701,57.231642,1.043888e+06,256.43443,45974.963300,924.830341,9.871285,8.981351,2.372830
std,947.662050,27.341205,5.018211e+04,141.01489,52757.043086,493.088489,24.040912,28.913690,7.638182
min,2106.000000,1.000000,1.011100e+06,10.00000,168.000000,50.000000,1.000000,0.100000,0.030000
25%,2604.000000,NaN,NaN,115.00000,26827.000000,750.000000,2.000000,1.500000,0.400000
50%,3722.000000,NaN,NaN,260.00000,38176.000000,750.000000,6.000000,5.250000,1.390000
75%,4378.000000,NaN,NaN,380.00000,64573.000000,1000.000000,12.000000,10.500000,2.770000
max,9023.000000,99.000000,1.701100e+06,978.00000,995507.000000,6000.000000,2508.000000,2508.000000,662.540000

In [4]:
iowa.columns

Index([u'Date', u'Store Number', u'City', u'Zip Code', u'County Number',
       u'County', u'Category', u'Category Name', u'Vendor Number',
       u'Item Number', u'Item Description', u'Bottle Volume (ml)',
       u'State Bottle Cost', u'State Bottle Retail', u'Bottles Sold',
       u'Sale (Dollars)', u'Volume Sold (Liters)', u'Volume Sold (Gallons)'],
      dtype='object')

In [5]:
iowa.isnull().sum()

#iowa.isnull().values.any()

Date                        0
Store Number                0
City                        0
Zip Code                    0
County Number            1077
County                   1077
Category                   68
Category Name             632
Vendor Number               0
Item Number                 0
Item Description            0
Bottle Volume (ml)          0
State Bottle Cost           0
State Bottle Retail         0
Bottles Sold                0
Sale (Dollars)              0
Volume Sold (Liters)        0
Volume Sold (Gallons)       0
dtype: int64

In [58]:
iowa = iowa[iowa['County Number'] > 0 ]
iowa = iowa[iowa['County'] > 0 ]
iowa = iowa[iowa['Category'] > 0 ]
iowa = iowa[iowa['Category Name'] > 0 ]
iowa.isnull().sum()

#iowa.drop_duplicates(inplace=True)

Date                     0
Store Number             0
City                     0
Zip Code                 0
County Number            0
County                   0
Category                 0
Category Name            0
Vendor Number            0
Item Number              0
Item Description         0
Bottle Volume (ml)       0
State Bottle Cost        0
State Bottle Retail      0
Bottles Sold             0
Sale (Dollars)           0
Volume Sold (Liters)     0
Volume Sold (Gallons)    0
Year                     0
dtype: int64

In [28]:
iowa.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Year
0,2015-11-04,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,12,$81.00,9.0,2.38,2015
1,2016-03-02,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,Tin Cup,750,$13.75,$20.63,2,$41.26,1.5,0.40,2016
2,2016-02-11,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.0,6.34,2016
3,2016-02-03,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,$9.50,$14.25,6,$85.50,10.5,2.77,2016
4,2015-08-18,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,$7.20,$10.80,12,$129.60,21.0,5.55,2015

In [29]:

iowa.Date = pd.to_datetime(iowa.Date)
iowa.head()
#print iowa['Date'].datetime.now()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Year
0,2015-11-04,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,12,$81.00,9.0,2.38,2015
1,2016-03-02,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,Tin Cup,750,$13.75,$20.63,2,$41.26,1.5,0.40,2016
2,2016-02-11,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.0,6.34,2016
3,2016-02-03,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,$9.50,$14.25,6,$85.50,10.5,2.77,2016
4,2015-08-18,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,$7.20,$10.80,12,$129.60,21.0,5.55,2015

In [30]:
#msk = (iowa['Date'].year >= 2015) & (iowa['Date'].year < 2016)
#iowa['Date'].mask(msk)
dates = pd.DatetimeIndex(iowa['Date'])

iowa['Year']=dates.year
iowa

#numpy.timedelta64(366,'D')

#iowa[iowa[dtype.Date('O' == 2015)]]

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Year
0,2015-11-04,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,12,$81.00,9.00,2.38,2015
1,2016-03-02,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,Tin Cup,750,$13.75,$20.63,2,$41.26,1.50,0.40,2016
2,2016-02-11,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.00,6.34,2016
3,2016-02-03,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,$9.50,$14.25,6,$85.50,10.50,2.77,2016
4,2015-08-18,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,$7.20,$10.80,12,$129.60,21.00,5.55,2015
5,2015-04-20,2569,CEDAR RAPIDS,52402,57.0,Linn,1041100.0,AMERICAN DRY GINS,205,31473,New Amsterdam Gin,1750,$13.32,$19.98,6,$119.88,10.50,2.77,2015
6,2015-08-05,2596,OTTUMWA,52501,90.0,Wapello,1051010.0,AMERICAN GRAPE BRANDIES,85,52806,Korbel Brandy,750,$6.66,$9.99,3,$29.97,2.25,0.59,2015
7,2015-06-25,3456,CLEAR LAKE,50428,17.0,Cerro Gordo,1012100.0,CANADIAN WHISKIES,65,10628,Canadian Club Whisky,1750,$15.75,$23.63,2,$47.26,3.50,0.92,2015
8,2016-01-04,4757,BONDURANT,50035,77.0,Polk,1032080.0,IMPORTED VODKA,370,34006,Absolut Swedish Vodka 80 Prf,750,$11.49,$17.24,4,$68.96,3.00,0.79,2016
9,2015-11-10,4346,SHELLSBURG,52332,6.0,Benton,1081315.0,CINNAMON SCHNAPPS,65,82610,Dekuyper Hot Damn!,1000,$7.62,$11.43,2,$22.86,2.00,0.53,2015
10,2015-09-28,2648,WEST DES MOINES,50265,77.0,Polk,1011250.0,SINGLE BARREL BOURBON WHISKIES,65,19235,Knob Creek Single Barrel Reserve,750,$26.24,$39.36,6,$236.16,4.50,1.19,2015
11,2015-10-28,2600,OSKALOOSA,52577,62.0,Mahaska,1071100.0,AMERICAN COCKTAILS,55,57148,Chi-Chi's Margarita W/tequila,1750,$6.00,$9.25,6,$55.50,10.50,2.77,2015
12,2015-01-22,3858,DAVENPORT,52806,82.0,Scott,1012100.0,CANADIAN WHISKIES,65,15248,Windsor Canadian Pet,1750,$8.92,$13.38,1,$13.38,1.75,0.46,2015
13,2016-02-29,4673,WEST POINT,52656,56.0,Lee,1081300.0,PEPPERMINT SCHNAPPS,322,75211,Kinky Liqueur,750,$10.00,$15.00,12,$180.00,9.00,2.38,2016
14,2016-01-04,2670,CORALVILLE,52241,52.0,Johnson,1031200.0,VODKA FLAVORED,380,41705,Uv Red (cherry) Vodka,1000,$7.50,$11.25,12,$135.00,12.00,3.17,2016
15,2015-06-10,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,4,$27.00,3.00,0.79,2015
16,2016-02-25,2130,WATERLOO,50703,7.0,Black Hawk,1031100.0,100 PROOF VODKA,297,35913,Five O'clock Vodka,200,$1.13,$1.70,48,$81.60,9.60,2.54,2016
17,2015-12-29,2600,OSKALOOSA,52577,62.0,Mahaska,1031200.0,VODKA FLAVORED,380,41989,Uv Cake Vodka,750,$6.50,$9.75,12,$117.00,9.00,2.38,2015
18,2015-12-26,4604,NEWTON,50208,50.0,Jasper,1081700.0,DISTILLED SPIRITS SPECIALTY,434,75087,Juarez Gold Dss,1000,$4.92,$7.38,24,$177.12,24.00,6.34,2015
19,2015-03-04,2614,DAVENPORT,52807,82.0,Scott,1012100.0,CANADIAN WHISKIES,434,13638,Lord Calvert Canadian Whisky,1750,$9.97,$14.96,6,$89.76,10.50,2.77,2015
20,2015-01-16,2590,CEDAR RAPIDS,52402,57.0,Linn,1031200.0,VODKA FLAVORED,971,41474,44 North Huckleberry,750,$14.25,$21.38,2,$42.76,1.50,0.40,2015
21,2015-01-13,3942,TOLEDO,52342,86.0,Tama,1012100.0,CANADIAN WHISKIES,115,11786,Black Velvet Traveler,750,$5.23,$7.85,12,$94.20,9.00,2.38,2015
22,2015-03-24,3981,SIOUX CENTER,51250,84.0,Sioux,1011100.0,BLENDED WHISKIES,260,25606,Seagrams 7 Crown Bl Whiskey,750,$7.00,$10.50,12,$126.00,9.00,2.38,2015
23,2015-11-12,4376,MASON CITY,50401,17.0,Cerro Gordo,1022100.0,TEQUILA,395,89196,Jose Cuervo Especial Reposado Tequila,750,$10.49,$15.74,12,$188.88,9.00,2.38,2015
24,2016-03-14,2618,CEDAR RAPIDS,52402,57.0,Linn,1031080.0,VODKA 80 PROOF,297,35926,Five O'clock PET Vodka,750,$3.37,$5.06,12,$60.72,9.00,2.38,2016
25,2015-02-03,3390,MILFORD,51351,30.0,Dickinson,1011300.0,TENNESSEE WHISKIES,85,26827,Jack Daniels Old #7 Black Lbl,1000,$17.90,$26.85,24,$644.40,24.00,6.34,2015
26,2015-11-23,3565,IOWA CITY,52246,52.0,Johnson,1012100.0,CANADIAN WHISKIES,260,11290,Crown Royal Canadian Whisky Mini,300,$7.35,$11.03,1,$11.03,0.30,0.08,2015
27,2015-04-21,3963,COUNCIL BLUFFS,51501,78.0,Pottawattamie,1011100.0,BLENDED WHISKIES,434,24156,Hawkeye Blend Whiskey,750,$3.50,$5.25,3,$15.75,2.25,0.59,2015
28,2015-12-01,4375,GRIMES,50111,77.0,Polk,1031080.0,VODKA 80 PROOF,380,37338,UV Vodka PET,1750,$10.99,$16.49,6,$98.94,10.50,2.77,2015
29,2015-01-14,2545,IOWA CITY,52245,52.0,Johnson,1081600.0,WHISKEY LIQUEUR,260,66199,Piehole Apple Pie Mini,500,$4.90,$7.35,1,$7.35,0.50,0.13,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270925,2015-01-05,2837,WATERLOO,50702,7.0,Black Hawk,1081200.0,CREAM LIQUEURS,260,68306,Emmets Irish Cream Liqueur,750,$6.00,$9.00,4,$36.00,3.00,0.79,2015
270926,2015-12-26,2478,ALTOONA,50009,77.0,Polk,1022100.0,TEQUILA,410,89646,Patron Anejo,750,$31.00,$46.50,6,$279.00,4.50,1.19,2015
270927,2015-08-31,2633,DES MOINES,50320,77.0,Polk,1031200.0,VODKA FLAVORED,260,77699,Smirnoff Orange,1000,$9.25,$13.88,12,$166.56,12.00,3.17,2015
270928,2015-10-07,3896,IOWA CITY,52240,52.0,Johnson,1031080.0,VODKA 80 PROOF,300,36904,Mccormick Vodka Pet,375,$1.80,$2.70,48,$129.60,18.00,4.76,2015
270929,2016-01-25,5070,WILTON,52778,70.0,Muscatine,1031080.0,VODKA 80 PROOF,380,37346,Phillips Vodka,750,$3.57,$5.36,4,$21.44,3.00,0.79,2016
270930,2015-10-13,4634,CEDAR RAPIDS,52402,57.0,Linn,1031080.0,VODKA 80 PROOF,297,35914,Five O'clock Vodka,375,$1.93,$2.90,12,$34.80,4.50,1.19,2015
270931,2015-05-26,2602,WEBSTER CITY,50595,40.0,Hamilton,1081900.0,MISC. AMERICAN CORDIALS & LIQUEURS,65,85526,Dekuyper Signature Blue Curacao,750,$5.25,$7.88,12,$94.56,9.00,2.38,2015
270932,2015-06-18,4604,NEWTON,50208,50.0,Jasper,1011300.0,TENNESSEE WHISKIES,85,26828,Jack Daniels Old #7 Black Lbl,1750,$29.67,$44.51,2,$89.02,3.50,0.92,2015
270933,2015-02-26,4987,AMES,50010,85.0,Story,1062310.0,SPICED RUM,260,43336,Captain Morgan Original Spiced,750,$9.00,$13.50,3,$40.50,2.25,0.59,2015
270934,2015-03-18,2623,SIOUX CITY,51104,97.0,Woodbury,1051110.0,BLACKBERRY BRANDIES,55,55068,Mr. Boston Blackberry Brandy,1750,$10.00,$15.00,2,$30.00,3.50,0.92,2015
270935,2015-06-08,5126,DES MOINES,50310,77.0,Polk,1011300.0,TENNESSEE WHISKIES,85,86670,Jack Daniel's Tennessee Honey,750,$15.07,$22.61,3,$67.83,2.25,0.59,2015
270936,2015-03-31,2552,CEDAR RAPIDS,52404,57.0,Linn,1022100.0,TEQUILA,395,89196,Jose Cuervo Especial Reposado Tequila,750,$10.49,$15.74,12,$188.88,9.00,2.38,2015
270937,2015-01-27,2553,CRESTON,50801,88.0,Union,1082900.0,MISC. IMPORTED CORDIALS & LIQUEURS,85,64676,Chambord Liqueur Royale De France,750,$18.56,$27.84,1,$27.84,0.75,0.20,2015
270938,2015-04-29,3890,CEDAR RAPIDS,52405,57.0,Linn,1031080.0,VODKA 80 PROOF,260,37994,Smirnoff Vodka 80 Prf,375,$4.75,$7.13,3,$21.39,1.12,0.30,2015
270939,2015-05-04,4876,HIAWATHA,52233,57.0,Linn,1031200.0,VODKA FLAVORED,380,42002,Uv Cake Vodka,500,$4.89,$7.34,6,$44.04,3.00,0.79,2015
270940,2015-01-21,2523,CENTERVILLE,52544,4.0,Appanoose,1012200.0,SCOTCH WHISKIES,305,4936,Famous Grouse Scotch,750,$12.03,$18.05,4,$72.20,3.00,0.79,2015
270941,2015-02-09,4856,LISBON,52253,57.0,Linn,1031080.0,VODKA 80 PROOF,55,35948,Fleischmann's Royal Vodka 80 Prf,1750,$6.68,$10.27,6,$61.62,10.50,2.77,2015
270942,2015-06-15,2512,IOWA CITY,52240,52.0,Johnson,1011100.0,BLENDED WHISKIES,65,24466,Kessler Blend Whiskey Traveler,750,$5.51,$8.27,12,$99.24,9.00,2.38,2015
270943,2015-10-21,4438,AMES,50010,85.0,Story,1011200.0,STRAIGHT BOURBON WHISKIES,65,19061,Jim Beam Mini,500,$6.83,$10.25,1,$10.25,0.50,0.13,2015
270944,2016-03-22,2620,WINDSOR HEIGHTS,50311,77.0,Polk,1081240.0,GREEN CREME DE MENTHE,434,79336,Paramount Creme De Menthe/green,750,$4.75,$7.13,2,$14.26,1.50,0.40,2016
270945,2015-06-11,2627,DES MOINES,50310,77.0,Polk,1062200.0,PUERTO RICO & VIRGIN ISLANDS RUM,55,44215,Barton Light Rum,100,$0.89,$1.34,48,$64.32,4.80,1.27,2015
270946,2015-11-24,5162,URBANDALE,50322,77.0,Polk,1031080.0,VODKA 80 PROOF,301,38176,Titos Vodka,750,$9.65,$14.48,4,$57.92,3.00,0.79,2015
270947,2015-05-12,4375,GRIMES,50111,77.0,Polk,1062310.0,SPICED RUM,260,43334,Captain Morgan Spiced Rum,375,$5.00,$7.50,6,$45.00,2.25,0.59,2015
270948,2015-04-08,2545,IOWA CITY,52245,52.0,Johnson,1062300.0,FLAVORED RUM,35,43145,Bacardi Pineapple Fusion,750,$8.50,$12.75,3,$38.25,2.25,0.59,2015
270949,2015-07-21,2529,CEDAR RAPIDS,52405,57.0,Linn,1031100.0,100 PROOF VODKA,300,36887,McCormick Vodka,1000,$4.13,$6.20,3,$18.60,3.00,0.79,2015
270950,2015-12-22,4057,DES MOINES,50316,77.0,Polk,1022100.0,TEQUILA,410,88291,Patron Tequila Silver Mini,300,$20.30,$30.45,4,$121.80,1.20,0.32,2015
270951,2015-11-04,5151,IDA GROVE,51445,47.0,Ida,1011200.0,STRAIGHT BOURBON WHISKIES,259,17956,Evan Williams Str Bourbon,750,$7.47,$11.21,3,$33.63,2.25,0.59,2015
270952,2015-10-20,5152,WATERLOO,50702,7.0,Black Hawk,1011300.0,TENNESSEE WHISKIES,85,26826,Jack Daniels Old #7 Black Lbl,750,$15.07,$22.61,6,$135.66,4.50,1.19,2015
270953,2015-11-20,3562,WEST BURLINGTON,52655,29.0,Des Moines,1082900.0,MISC. IMPORTED CORDIALS & LIQUEURS,192,65258,Jagermeister Liqueur,1750,$26.05,$39.08,6,$234.48,10.50,2.77,2015
270954,2015-01-27,4446,URBANDALE,50322,77.0,Polk,1031080.0,VODKA 80 PROOF,260,37993,Smirnoff Vodka 80 Prf,200,$2.75,$4.13,8,$33.04,1.60,0.42,2015

In [72]:
iowa_subset = iowa.loc[:,['Store Number','Year','Sale (Dollars)','Date']]
iowa_subset

            Store Number  Year Sale (Dollars)       Date
Date
2015-11-04          3717  2015         $81.00 2015-11-04
2016-03-02          2614  2016         $41.26 2016-03-02
2016-02-11          2106  2016        $453.36 2016-02-11
2016-02-03          2501  2016         $85.50 2016-02-03
2015-08-18          3654  2015        $129.60 2015-08-18
2015-04-20          2569  2015        $119.88 2015-04-20
2015-08-05          2596  2015         $29.97 2015-08-05
2015-06-25          3456  2015         $47.26 2015-06-25
2016-01-04          4757  2016         $68.96 2016-01-04
2015-11-10          4346  2015         $22.86 2015-11-10
2015-09-28          2648  2015        $236.16 2015-09-28
2015-10-28          2600  2015         $55.50 2015-10-28
2015-01-22          3858  2015         $13.38 2015-01-22
2016-02-29          4673  2016        $180.00 2016-02-29
2016-01-04          2670  2016        $135.00 2016-01-04
2015-06-10          3717  2015         $27.00 2015-06-10
2016-02-25          2130  2016         $81.60 2016-02-25
2015-12-29          2600  2015        $117.00 2015-12-29
2015-12-26          4604  2015        $177.12 2015-12-26
2015-03-04          2614  2015         $89.76 2015-03-04
2015-01-16          2590  2015         $42.76 2015-01-16
2015-01-13          3942  2015         $94.20 2015-01-13
2015-03-24          3981  2015        $126.00 2015-03-24
2015-11-12          4376  2015        $188.88 2015-11-12
2016-03-14          2618  2016         $60.72 2016-03-14
2015-02-03          3390  2015        $644.40 2015-02-03
2015-11-23          3565  2015         $11.03 2015-11-23
2015-04-21          3963  2015         $15.75 2015-04-21
2015-12-01          4375  2015         $98.94 2015-12-01
2015-01-14          2545  2015          $7.35 2015-01-14
...                  ...   ...            ...        ...
2015-01-05          2837  2015         $36.00 2015-01-05
2015-12-26          2478  2015        $279.00 2015-12-26
2015-08-31          2633  2015        $166.56 2015-08-31
2015-10-07          3896  2015        $129.60 2015-10-07
2016-01-25          5070  2016         $21.44 2016-01-25
2015-10-13          4634  2015         $34.80 2015-10-13
2015-05-26          2602  2015         $94.56 2015-05-26
2015-06-18          4604  2015         $89.02 2015-06-18
2015-02-26          4987  2015         $40.50 2015-02-26
2015-03-18          2623  2015         $30.00 2015-03-18
2015-06-08          5126  2015         $67.83 2015-06-08
2015-03-31          2552  2015        $188.88 2015-03-31
2015-01-27          2553  2015         $27.84 2015-01-27
2015-04-29          3890  2015         $21.39 2015-04-29
2015-05-04          4876  2015         $44.04 2015-05-04
2015-01-21          2523  2015         $72.20 2015-01-21
2015-02-09          4856  2015         $61.62 2015-02-09
2015-06-15          2512  2015         $99.24 2015-06-15
2015-10-21          4438  2015         $10.25 2015-10-21
2016-03-22          2620  2016         $14.26 2016-03-22
2015-06-11          2627  2015         $64.32 2015-06-11
2015-11-24          5162  2015         $57.92 2015-11-24
2015-05-12          4375  2015         $45.00 2015-05-12
2015-04-08          2545  2015         $38.25 2015-04-08
2015-07-21          2529  2015         $18.60 2015-07-21
2015-12-22          4057  2015        $121.80 2015-12-22
2015-11-04          5151  2015         $33.63 2015-11-04
2015-10-20          5152  2015        $135.66 2015-10-20
2015-11-20          3562  2015        $234.48 2015-11-20
2015-01-27          4446  2015         $33.04 2015-01-27

[269258 rows x 4 columns]

In [73]:


l = pd.to_datetime('20150101', format='%Y%m%d')
r = pd.to_datetime('20160101', format='%Y%m%d')
rng = pd.date_range(l,r)
rng
#mask = (iowa['Date'] > l) & (iowa['Date'] < r)

#iowa['Date']
#iowa = iowa.irow[mask]
#print iowa
#3iowa.loc[:,(iowa['Date'] > l) & (iowa['Date'] < r)]

DatetimeIndex(['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04',
               '2015-01-05', '2015-01-06', '2015-01-07', '2015-01-08',
               '2015-01-09', '2015-01-10',
               ...
               '2015-12-23', '2015-12-24', '2015-12-25', '2015-12-26',
               '2015-12-27', '2015-12-28', '2015-12-29', '2015-12-30',
               '2015-12-31', '2016-01-01'],
              dtype='datetime64[ns]', length=366, freq='D')

In [77]:
iowa_subset.index= iowa_subset['Date']
iowa_subset.loc[rng]

            Store Number    Year Sale (Dollars)       Date
Date
2015-01-01           NaN     NaN            NaN        NaT
2015-01-02           NaN     NaN            NaN        NaT
2015-01-03           NaN     NaN            NaN        NaT
2015-01-04           NaN     NaN            NaN        NaT
2015-01-05        3562.0  2015.0        $117.00 2015-01-05
2015-01-05        2643.0  2015.0         $39.36 2015-01-05
2015-01-05        4752.0  2015.0         $90.00 2015-01-05
2015-01-05        2584.0  2015.0         $70.56 2015-01-05
2015-01-05        4572.0  2015.0         $17.99 2015-01-05
2015-01-05        2613.0  2015.0         $23.58 2015-01-05
2015-01-05        2538.0  2015.0         $59.76 2015-01-05
2015-01-05        2528.0  2015.0        $206.88 2015-01-05
2015-01-05        2506.0  2015.0         $61.90 2015-01-05
2015-01-05        4180.0  2015.0         $72.00 2015-01-05
2015-01-05        4421.0  2015.0        $121.50 2015-01-05
2015-01-05        4307.0  2015.0        $119.40 2015-01-05
2015-01-05        2190.0  2015.0         $25.06 2015-01-05
2015-01-05        4258.0  2015.0        $112.50 2015-01-05
2015-01-05        2538.0  2015.0        $216.96 2015-01-05
2015-01-05        2521.0  2015.0        $322.20 2015-01-05
2015-01-05        2538.0  2015.0         $46.38 2015-01-05
2015-01-05        2573.0  2015.0        $274.32 2015-01-05
2015-01-05        2605.0  2015.0         $10.70 2015-01-05
2015-01-05        3829.0  2015.0        $148.56 2015-01-05
2015-01-05        5054.0  2015.0        $171.00 2015-01-05
2015-01-05        4312.0  2015.0        $151.20 2015-01-05
2015-01-05        4415.0  2015.0        $124.20 2015-01-05
2015-01-05        3918.0  2015.0         $39.03 2015-01-05
2015-01-05        2643.0  2015.0        $108.00 2015-01-05
2015-01-05        4307.0  2015.0         $11.43 2015-01-05
...                  ...     ...            ...        ...
2015-12-30        4902.0  2015.0         $40.64 2015-12-30
2015-12-30        4988.0  2015.0        $179.94 2015-12-30
2015-12-30        3858.0  2015.0         $16.62 2015-12-30
2015-12-30        3888.0  2015.0        $242.88 2015-12-30
2015-12-30        2550.0  2015.0         $51.03 2015-12-30
2015-12-30        4134.0  2015.0         $32.98 2015-12-30
2015-12-30        2627.0  2015.0         $30.03 2015-12-30
2015-12-30        4367.0  2015.0         $17.25 2015-12-30
2015-12-30        2571.0  2015.0         $67.14 2015-12-30
2015-12-31        4725.0  2015.0         $44.58 2015-12-31
2015-12-31        4374.0  2015.0         $20.40 2015-12-31
2015-12-31        4617.0  2015.0        $148.68 2015-12-31
2015-12-31        4617.0  2015.0         $50.12 2015-12-31
2015-12-31        4617.0  2015.0         $18.50 2015-12-31
2015-12-31        4617.0  2015.0         $52.45 2015-12-31
2015-12-31        4695.0  2015.0        $113.28 2015-12-31
2015-12-31        4165.0  2015.0          $9.90 2015-12-31
2015-12-31        9002.0  2015.0       $6226.08 2015-12-31
2015-12-31        4725.0  2015.0         $74.28 2015-12-31
2015-12-31        4725.0  2015.0         $63.00 2015-12-31
2015-12-31        4374.0  2015.0        $132.78 2015-12-31
2015-12-31        4165.0  2015.0         $47.10 2015-12-31
2015-12-31        4165.0  2015.0         $41.31 2015-12-31
2015-12-31        4374.0  2015.0         $89.16 2015-12-31
2015-12-31        4165.0  2015.0         $18.44 2015-12-31
2015-12-31        4165.0  2015.0         $19.50 2015-12-31
2015-12-31        5089.0  2015.0        $118.80 2015-12-31
2015-12-31        4617.0  2015.0         $18.00 2015-12-31
2015-12-31        4374.0  2015.0         $89.58 2015-12-31
2016-01-01           NaN     NaN            NaN        NaT

[218493 rows x 4 columns]

In [76]:
#iowa.isnull().sum()
iowa_by_store = iowa_subset.groupby('Store Number')

In [13]:
# Clean up missing values in multiple DataFrame columns
#df = iowa.fillna({
#    'col1': 'missing',
#    'col2': '99.999',
#    'col3': '999',
#    'col4': 'missing',
#    'col5': 'missing',
#    'col6': '99'
#})

269258

269258

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Year
270950,2015-12-22,4057,DES MOINES,50316,77.0,Polk,1022100.0,TEQUILA,410,88291,Patron Tequila Silver Mini,300,$20.30,$30.45,4,$121.80,1.20,0.32,2015
270951,2015-11-04,5151,IDA GROVE,51445,47.0,Ida,1011200.0,STRAIGHT BOURBON WHISKIES,259,17956,Evan Williams Str Bourbon,750,$7.47,$11.21,3,$33.63,2.25,0.59,2015
270952,2015-10-20,5152,WATERLOO,50702,7.0,Black Hawk,1011300.0,TENNESSEE WHISKIES,85,26826,Jack Daniels Old #7 Black Lbl,750,$15.07,$22.61,6,$135.66,4.50,1.19,2015
270953,2015-11-20,3562,WEST BURLINGTON,52655,29.0,Des Moines,1082900.0,MISC. IMPORTED CORDIALS & LIQUEURS,192,65258,Jagermeister Liqueur,1750,$26.05,$39.08,6,$234.48,10.50,2.77,2015
270954,2015-01-27,4446,URBANDALE,50322,77.0,Polk,1031080.0,VODKA 80 PROOF,260,37993,Smirnoff Vodka 80 Prf,200,$2.75,$4.13,8,$33.04,1.60,0.42,2015